### ISSUE TITLE
Profile page for Dietitian

### ISSUE THREAD

**Issue by kutagorn** [nutrition-ist/fit-nutrition-front#6]

**Comment by kutagorn** [comment]
I would love it if someone can tell me what do we want in the dietatian profile page. 
I am thinking of;

- My Patients
- My Recipes
- My Appointments

Or we can make the profile page more like a portfilio and add settings then add the things I said in to Dietatian dashboard. 
So the profile everyone can see would be like;

-Profile Picture
-Name and title
- Cell Number
- About Me
- Adress
-Highlighted Recipes ? 

and when the dietation logs in they can see one more button with Profile Settings.

**Comment by hazalmaslan** [comment]
we will have both pages. 

1. Dietitian profile page: 
  - Cell Number
  - About Me
  - Adress
  - Highlighted Recipes ?
 2. Dietitian dashboard, they see this after logging in
  -  My Patients
  - My Recipes
  - My Appointments

**Comment by ozgurozbek** [comment]
You'll have 2 variables to check whether the dietitian is a Manager/Organisation or a low level dietitian.

You must have My Patients, My Recipes, My Appointments. You must also have name, contact details, image, description if it exists, organization if under one.

For a manager you must have My Patients, Organization Patients, My Recipes, Organization Recipes, My Appointments, Organization Appointments and Organization (Which will show every Dietitian, Patient and Recipe under that organization, basically a hub for everything organization/managed by the manager etc.

I'll get the wireframe done hopefully tonight so you can be more informed with the page designs, but I'll send a demo

**Comment by ozgurozbek** [comment]
![image](https://github.com/user-attachments/assets/e73d296b-89e6-4396-ac81-a9167120bc84)

Left panel should be hidden by default, depending on login. center rectangle should be hidden by default unless it's your profile or someone else's profile who is managed by you

**Comment by kutagorn** [comment]
The Manager/Organisation should be their own issue because It is a large task. 

so for the dietatian profile I will add;

- Dietitian profile page:
- Cell Number
- About Me
- Adress
- Highlighted Recipes ?

And when I make a dashboard for the dietatian I will add;

- My Patients
- My Recipes
- My Appointments

**Comment by hazalmaslan** [comment]
I haven't created a organization user yet. I think we can add it after we have a base site with dietitians and patients

**Comment by ozgurozbek** [comment]
> The Manager/Organisation should be their own issue because It is a large task.
> 
> so for the dietitian profile I will add;
> 
> * Dietitian profile page:
> * Cell Number
> * About Me
> * Adress
> * Highlighted Recipes ?
> 
> And when I make a dashboard for the dietitian I will add;
> 
> * My Patients
> * My Recipes
> * My Appointments

It being a large task doesn't mean every little thing in it should be an issue, because they aren't issues - literally. Issue board is not a todo list.

You can put the dashboard in the dietitian page, and not show it if the user doesn't own the dietitian page displayed, ie: every dietitian page should have the profile content, but your own dietitian page should have the dashboard content.
